baseURL: /
languageCode: en-US
defaultContentLanguage: en
title: Data Science for Everyone
theme: hugo-theme-learn
metaDataFormat: yaml
defaultContentLanguageInSubdir: yes
params:
  author: Jacob Rozran
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  description: A Place for Anyone to Learn Data Science 
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: no
  editURL: https://github.com/RLE-Analytics/ds4e/tree/main/content
  showVisitedLinks: yes
  titleSeparator: '::'
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  en:
    landingPageName: <i class='fas fa-home'></i> Home
    landingPageURL: /en
    languageName: English
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> GitHub repo
          url: https://github.com/RLE-Analytics/ds4e
          weight: 10
        - name: <i class='fas fa-fw fa-camera'></i> Showcases
          url: showcase
          weight: 11
        - identifier: hugodoc
          name: <i class='fas fa-fw fa-bookmark'></i> Hugo Documentation
          url: https://gohugo.io/
          weight: 20
        - name: <i class='fas fa-fw fa-bullhorn'></i> Credits
          url: /credits
          weight: 30
    title: Data Science for Everyone
    weight: 1
